name: Rustyn Rose
favicon: null
layout_spectrum: 0.7977923394646496
typography_spectrum: 0.16230401792563498
title: Rustyn Rose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7929385674651712
  lightness: 0.4055659417062998
  saturation: 0.08026604820042849
  rhythmicContrast: 0.7265548370778561
purpose: []
